/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frotaveiculos.telas;

/**
 *
 * @author Adilson
 */
public class GTelaTrocaOleo extends javax.swing.JFrame {

    /**
     * Creates new form GTelaAbastecimento
     */
    public GTelaTrocaOleo() {
	initComponents();
	setBounds(300,50,700,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTrocaOleoPlacaVeiculo = new javax.swing.JComboBox<>();
        jComboBoxTrocaOleoMotorista = new javax.swing.JComboBox<>();
        jComboBoxTrocaOleoSetor = new javax.swing.JComboBox<>();
        jLabelTrocaOleoPlacaVeiculo = new javax.swing.JLabel();
        jLabelTrocaOleoMotorista = new javax.swing.JLabel();
        jLabelTrocaOleoSetor = new javax.swing.JLabel();
        jLabelTrocaOleoIDVeiculo = new javax.swing.JLabel();
        jLabelTrocaOleoIDMotorista = new javax.swing.JLabel();
        jLabelTrocaOleoIDSetor = new javax.swing.JLabel();
        jLabelTrocaOleoOdometro = new javax.swing.JLabel();
        jLabelTrocaOleoData = new javax.swing.JLabel();
        jLabelTrocaOleoLocalServico = new javax.swing.JLabel();
        jLabelTrocaOleoCusto = new javax.swing.JLabel();
        jLabelTrocaOleoDetalhes = new javax.swing.JLabel();
        jLabelTrocaOleoCidade = new javax.swing.JLabel();
        jLabelTrocaOleoEstado = new javax.swing.JLabel();
        jTextFieldTrocaOleoLocalServico = new javax.swing.JTextField();
        jTextFieldTrocaOleoCusto = new javax.swing.JTextField();
        jComboBoxTrocaOleoEstado = new javax.swing.JComboBox<>();
        jLabelTrocaOleoCamposObrigatorios = new javax.swing.JLabel();
        jTextFieldTrocaOleoDetalhes = new javax.swing.JTextField();
        jButtonTrocaOleoSalvar = new javax.swing.JButton();
        jButtonTrocaOleoLimpar = new javax.swing.JButton();
        jButtonTrocaOleoAlterar = new javax.swing.JButton();
        jButtonTrocaOleoExcluir = new javax.swing.JButton();
        jLabelTrocaOleoFoto = new javax.swing.JLabel();
        jTextFieldTrocaOleoCidade = new javax.swing.JTextField();
        jTextFieldTrocaOleoData = new javax.swing.JTextField();
        jTextFieldTrocaOleoOdometro = new javax.swing.JTextField();
        jLabelTrocaOleoProximaTroca = new javax.swing.JLabel();
        jLabelTrocaOleoPesquisarID = new javax.swing.JLabel();
        jTextFieldTrocaOleoProximaTroca = new javax.swing.JTextField();
        jTextFieldTrocaOleoPesquisarID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Troca de Óleo");

        jComboBoxTrocaOleoPlacaVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTrocaOleoPlacaVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABC 3030", "ABC 4444" }));

        jComboBoxTrocaOleoMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTrocaOleoMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adilson", "Juca Bala", "Zé Bolha" }));

        jComboBoxTrocaOleoSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxTrocaOleoSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor A", "Setor B", "Setor C" }));

        jLabelTrocaOleoPlacaVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoPlacaVeiculo.setText("*Placa Veiculo:");

        jLabelTrocaOleoMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoMotorista.setText("*Motorista:");

        jLabelTrocaOleoSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoSetor.setText("*Setor:");

        jLabelTrocaOleoIDVeiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoIDVeiculo.setText("IDVeiculo");

        jLabelTrocaOleoIDMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoIDMotorista.setText("IDMotorista");

        jLabelTrocaOleoIDSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoIDSetor.setText("IDSetor");

        jLabelTrocaOleoOdometro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoOdometro.setText("*Odômetro:");

        jLabelTrocaOleoData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoData.setText("*Data:");

        jLabelTrocaOleoLocalServico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoLocalServico.setText("Local Serviço:");

        jLabelTrocaOleoCusto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoCusto.setText("*Custo R$:");

        jLabelTrocaOleoDetalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoDetalhes.setText("Detalhes:");

        jLabelTrocaOleoCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoCidade.setText("Cidade:");

        jLabelTrocaOleoEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoEstado.setText("Estado:");

        jTextFieldTrocaOleoLocalServico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldTrocaOleoCusto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBoxTrocaOleoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabelTrocaOleoCamposObrigatorios.setText("* Campos Obrigatórios.");

        jTextFieldTrocaOleoDetalhes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonTrocaOleoSalvar.setText("Salvar");

        jButtonTrocaOleoLimpar.setText("Limpar");

        jButtonTrocaOleoAlterar.setText("Alterar");

        jButtonTrocaOleoExcluir.setText("Excluir");

        jLabelTrocaOleoFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/4TrocaOleo.png"))); // NOI18N

        jTextFieldTrocaOleoCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldTrocaOleoData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldTrocaOleoOdometro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelTrocaOleoProximaTroca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoProximaTroca.setText("Próxima Troca:");

        jLabelTrocaOleoPesquisarID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTrocaOleoPesquisarID.setText("Pesquisar ID:");

        jTextFieldTrocaOleoProximaTroca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldTrocaOleoPesquisarID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/pesquisar 20x20.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jButtonTrocaOleoSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTrocaOleoLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTrocaOleoAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTrocaOleoExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelTrocaOleoMotorista)
                                        .addComponent(jLabelTrocaOleoPlacaVeiculo)
                                        .addComponent(jLabelTrocaOleoPesquisarID)
                                        .addComponent(jLabelTrocaOleoSetor))
                                    .addComponent(jLabelTrocaOleoCidade)
                                    .addComponent(jLabelTrocaOleoLocalServico))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTrocaOleoDetalhes)
                                            .addComponent(jLabelTrocaOleoCusto)
                                            .addComponent(jLabelTrocaOleoOdometro)
                                            .addComponent(jLabelTrocaOleoData))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelTrocaOleoProximaTroca)
                                        .addGap(18, 18, 18)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTrocaOleoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxTrocaOleoMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxTrocaOleoPlacaVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxTrocaOleoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelTrocaOleoIDMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTrocaOleoIDVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTrocaOleoIDSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(220, 220, 220))
                            .addComponent(jTextFieldTrocaOleoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldTrocaOleoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTrocaOleoEstado)
                                .addGap(31, 31, 31)
                                .addComponent(jComboBoxTrocaOleoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTrocaOleoProximaTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrocaOleoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTrocaOleoLocalServico, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTrocaOleoPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldTrocaOleoOdometro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(jLabelTrocaOleoFoto))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTrocaOleoCamposObrigatorios)
                        .addGap(12, 12, 12)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTrocaOleoPesquisarID)
                                .addComponent(jTextFieldTrocaOleoPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTrocaOleoPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrocaOleoIDVeiculo)
                            .addComponent(jLabelTrocaOleoPlacaVeiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTrocaOleoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrocaOleoMotorista)
                            .addComponent(jLabelTrocaOleoIDMotorista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTrocaOleoSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrocaOleoSetor)
                            .addComponent(jLabelTrocaOleoIDSetor))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTrocaOleoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrocaOleoData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTrocaOleoOdometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrocaOleoOdometro)))
                    .addComponent(jLabelTrocaOleoFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTrocaOleoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrocaOleoCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrocaOleoProximaTroca)
                    .addComponent(jTextFieldTrocaOleoProximaTroca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTrocaOleoDetalhes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTrocaOleoDetalhes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTrocaOleoLocalServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrocaOleoLocalServico))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrocaOleoCidade)
                    .addComponent(jLabelTrocaOleoEstado)
                    .addComponent(jComboBoxTrocaOleoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTrocaOleoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTrocaOleoSalvar)
                    .addComponent(jButtonTrocaOleoLimpar)
                    .addComponent(jButtonTrocaOleoAlterar)
                    .addComponent(jButtonTrocaOleoExcluir))
                .addGap(58, 58, 58)
                .addComponent(jLabelTrocaOleoCamposObrigatorios)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GTelaTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GTelaTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GTelaTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GTelaTrocaOleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GTelaTrocaOleo().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTrocaOleoAlterar;
    private javax.swing.JButton jButtonTrocaOleoExcluir;
    private javax.swing.JButton jButtonTrocaOleoLimpar;
    private javax.swing.JButton jButtonTrocaOleoSalvar;
    private javax.swing.JComboBox<String> jComboBoxTrocaOleoEstado;
    private javax.swing.JComboBox<String> jComboBoxTrocaOleoMotorista;
    private javax.swing.JComboBox<String> jComboBoxTrocaOleoPlacaVeiculo;
    private javax.swing.JComboBox<String> jComboBoxTrocaOleoSetor;
    private javax.swing.JLabel jLabelTrocaOleoCamposObrigatorios;
    private javax.swing.JLabel jLabelTrocaOleoCidade;
    private javax.swing.JLabel jLabelTrocaOleoCusto;
    private javax.swing.JLabel jLabelTrocaOleoData;
    private javax.swing.JLabel jLabelTrocaOleoDetalhes;
    private javax.swing.JLabel jLabelTrocaOleoEstado;
    private javax.swing.JLabel jLabelTrocaOleoFoto;
    private javax.swing.JLabel jLabelTrocaOleoIDMotorista;
    private javax.swing.JLabel jLabelTrocaOleoIDSetor;
    private javax.swing.JLabel jLabelTrocaOleoIDVeiculo;
    private javax.swing.JLabel jLabelTrocaOleoLocalServico;
    private javax.swing.JLabel jLabelTrocaOleoMotorista;
    private javax.swing.JLabel jLabelTrocaOleoOdometro;
    private javax.swing.JLabel jLabelTrocaOleoPesquisarID;
    private javax.swing.JLabel jLabelTrocaOleoPlacaVeiculo;
    private javax.swing.JLabel jLabelTrocaOleoProximaTroca;
    private javax.swing.JLabel jLabelTrocaOleoSetor;
    private javax.swing.JTextField jTextFieldTrocaOleoCidade;
    private javax.swing.JTextField jTextFieldTrocaOleoCusto;
    private javax.swing.JTextField jTextFieldTrocaOleoData;
    private javax.swing.JTextField jTextFieldTrocaOleoDetalhes;
    private javax.swing.JTextField jTextFieldTrocaOleoLocalServico;
    private javax.swing.JTextField jTextFieldTrocaOleoOdometro;
    private javax.swing.JTextField jTextFieldTrocaOleoPesquisarID;
    private javax.swing.JTextField jTextFieldTrocaOleoProximaTroca;
    // End of variables declaration//GEN-END:variables
}
