/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frotaveiculos.telas;

/**
 *
 * @author Adilson
 */
public class GTelaCadastroMotorista extends javax.swing.JFrame {

    /**
     * Creates new form GTelaCadastroMotorista
     */
    public GTelaCadastroMotorista() {
	initComponents();
	setBounds(300,50,700,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroMotoristaNomeMotorista = new javax.swing.JLabel();
        jLabelCadastroMotoristaTelefone = new javax.swing.JLabel();
        jLabelCadastroMotoristaDescricaoMotorista = new javax.swing.JLabel();
        jTextFieldCadastroMotoristaNomeMotorista = new javax.swing.JTextField();
        jTextFieldCadastroMotoristaTelefone = new javax.swing.JTextField();
        jTextFieldCadastroMotoristaDescricaoMotorista = new javax.swing.JTextField();
        jLabelCadastroMotoristaCamposObrigatorios = new javax.swing.JLabel();
        jButtonCadastroMotoristaSalvar = new javax.swing.JButton();
        jButtonCadastroMotoristaLimpar = new javax.swing.JButton();
        jButtonCadastroMotoristaAlterar = new javax.swing.JButton();
        jButtonCadastroMotoristaExcluir = new javax.swing.JButton();
        jLabelCadastroMotoristaPesquisarNome = new javax.swing.JLabel();
        jTextFieldCadastroMotoristaPesquisarNome = new javax.swing.JTextField();
        jLabelCadastroMotoristaIDMotorista = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Motorista");

        jLabelCadastroMotoristaNomeMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroMotoristaNomeMotorista.setText("*Nome do Motorista:");

        jLabelCadastroMotoristaTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroMotoristaTelefone.setText("Telefone:");

        jLabelCadastroMotoristaDescricaoMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroMotoristaDescricaoMotorista.setText("Descrição Motorista:");

        jLabelCadastroMotoristaCamposObrigatorios.setText("* Campos Obrigatórios.");

        jButtonCadastroMotoristaSalvar.setText("Salvar");

        jButtonCadastroMotoristaLimpar.setText("Limpar");

        jButtonCadastroMotoristaAlterar.setText("Alterar");

        jButtonCadastroMotoristaExcluir.setText("Exluir");

        jLabelCadastroMotoristaPesquisarNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroMotoristaPesquisarNome.setText("Pesquisar Nome:");

        jLabelCadastroMotoristaIDMotorista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroMotoristaIDMotorista.setText("IDMotorista");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/pesquisar 20x20.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroMotoristaTelefone)
                    .addComponent(jLabelCadastroMotoristaNomeMotorista)
                    .addComponent(jLabelCadastroMotoristaDescricaoMotorista)
                    .addComponent(jLabelCadastroMotoristaPesquisarNome))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldCadastroMotoristaDescricaoMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addComponent(jTextFieldCadastroMotoristaTelefone)
                        .addComponent(jTextFieldCadastroMotoristaNomeMotorista))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCadastroMotoristaPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCadastroMotoristaIDMotorista))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCadastroMotoristaSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroMotoristaLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroMotoristaAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastroMotoristaExcluir)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroMotoristaCamposObrigatorios)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCadastroMotoristaPesquisarNome)
                            .addComponent(jTextFieldCadastroMotoristaPesquisarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCadastroMotoristaNomeMotorista)
                            .addComponent(jTextFieldCadastroMotoristaNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCadastroMotoristaTelefone)
                            .addComponent(jTextFieldCadastroMotoristaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCadastroMotoristaDescricaoMotorista)
                            .addComponent(jTextFieldCadastroMotoristaDescricaoMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCadastroMotoristaSalvar)
                            .addComponent(jButtonCadastroMotoristaLimpar)
                            .addComponent(jButtonCadastroMotoristaAlterar)
                            .addComponent(jButtonCadastroMotoristaExcluir)))
                    .addComponent(jLabelCadastroMotoristaIDMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabelCadastroMotoristaCamposObrigatorios)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GTelaCadastroMotorista().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastroMotoristaAlterar;
    private javax.swing.JButton jButtonCadastroMotoristaExcluir;
    private javax.swing.JButton jButtonCadastroMotoristaLimpar;
    private javax.swing.JButton jButtonCadastroMotoristaSalvar;
    private javax.swing.JLabel jLabelCadastroMotoristaCamposObrigatorios;
    private javax.swing.JLabel jLabelCadastroMotoristaDescricaoMotorista;
    private javax.swing.JLabel jLabelCadastroMotoristaIDMotorista;
    private javax.swing.JLabel jLabelCadastroMotoristaNomeMotorista;
    private javax.swing.JLabel jLabelCadastroMotoristaPesquisarNome;
    private javax.swing.JLabel jLabelCadastroMotoristaTelefone;
    private javax.swing.JTextField jTextFieldCadastroMotoristaDescricaoMotorista;
    private javax.swing.JTextField jTextFieldCadastroMotoristaNomeMotorista;
    private javax.swing.JTextField jTextFieldCadastroMotoristaPesquisarNome;
    private javax.swing.JTextField jTextFieldCadastroMotoristaTelefone;
    // End of variables declaration//GEN-END:variables
}
