/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frotaveiculos.telas;

import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Adilson
 */
public class GTelaCadastroSetor extends javax.swing.JFrame {

    /**
     * Creates new form GTelaCadastroSetor
     */
    public GTelaCadastroSetor() {
	initComponents();
	setBounds(300,50,700,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroSetorPesquisarSetor = new javax.swing.JLabel();
        jLabelCadastroSetorNome = new javax.swing.JLabel();
        jTextFieldPesquisaSetor = new javax.swing.JTextField();
        jTextFieldCadastroSetor = new javax.swing.JTextField();
        jButtonCadastroSetorSalvar = new javax.swing.JButton();
        jButtonCadastroSetorLimpar = new javax.swing.JButton();
        jButtonCadastroSetorAlterar = new javax.swing.JButton();
        jButtonCadastroSetorExcluir = new javax.swing.JButton();
        jButtonPesquisarSetor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelIDSetor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Setor");

        jLabelCadastroSetorPesquisarSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroSetorPesquisarSetor.setText("Pesquisar Setor:");

        jLabelCadastroSetorNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCadastroSetorNome.setText("Nome do Setor:");

        jTextFieldPesquisaSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldCadastroSetor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButtonCadastroSetorSalvar.setText("Salvar");
        jButtonCadastroSetorSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroSetorSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroSetorLimpar.setText("Limpar");

        jButtonCadastroSetorAlterar.setText("Alterar");
        jButtonCadastroSetorAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroSetorAlterarActionPerformed(evt);
            }
        });

        jButtonCadastroSetorExcluir.setText("Excluir");

        jButtonPesquisarSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/pesquisar 20x20.png"))); // NOI18N

        jLabel3.setText("*Campos obrigatórios.");

        jLabelIDSetor.setText("IDSetor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCadastroSetorPesquisarSetor)
                                .addComponent(jLabelCadastroSetorNome))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonCadastroSetorSalvar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCadastroSetorLimpar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCadastroSetorAlterar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonCadastroSetorExcluir))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPesquisaSetor)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPesquisarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelIDSetor))
                                    .addComponent(jTextFieldCadastroSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPesquisarSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCadastroSetorPesquisarSetor)
                                .addComponent(jTextFieldPesquisaSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelIDSetor)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroSetorNome)
                    .addComponent(jTextFieldCadastroSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroSetorSalvar)
                    .addComponent(jButtonCadastroSetorLimpar)
                    .addComponent(jButtonCadastroSetorAlterar)
                    .addComponent(jButtonCadastroSetorExcluir))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroSetorSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroSetorSalvarActionPerformed
	Session sessao = null;

	try {
	    sessao = HibernateUtil.getSessionFactory().openSession();
	    Transaction t = sessao.beginTransaction();
	    TelaCadastroSetor c = new TelaCadastroSetor();
	    c.setNome(jTextFieldCadastroSetor.getText());
	    sessao.save(c);
	    t.commit();
	    JOptionPane.showMessageDialog(null, "Cadastro Efetuado");
	} catch (HibernateException he) {
	    he.printStackTrace();
	} finally {
	    sessao.close();
	}
    }//GEN-LAST:event_jButtonCadastroSetorSalvarActionPerformed

    private void jButtonCadastroSetorAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroSetorAlterarActionPerformed
	List resultado = null;

	try {
	    Session sessao = HibernateUtil.getSessionFactory().openSession();

	    int codigo = 1;
	    org.hibernate.Query q = sessao.createQuery("FROM tb_setor");
	    resultado = q.list();

	    for (Object o : resultado) {
		nome_setor p = (nome_setor) o;
		System.out.println("Código: " + p.getCodigo());
		System.out.println("Nome Setor: " + p.getNome());
		//JOptionPane.showMessageDialog(null, p.getNome());
	    }

	} catch (HibernateException he) {
	    he.printStackTrace();
	}
    
    }//GEN-LAST:event_jButtonCadastroSetorAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GTelaCadastroSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GTelaCadastroSetor().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroSetorAlterar;
    private javax.swing.JButton jButtonCadastroSetorExcluir;
    private javax.swing.JButton jButtonCadastroSetorLimpar;
    private javax.swing.JButton jButtonCadastroSetorSalvar;
    private javax.swing.JButton jButtonPesquisarSetor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadastroSetorNome;
    private javax.swing.JLabel jLabelCadastroSetorPesquisarSetor;
    private javax.swing.JLabel jLabelIDSetor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCadastroSetor;
    private javax.swing.JTextField jTextFieldPesquisaSetor;
    // End of variables declaration//GEN-END:variables
}
