/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frotaveiculos.telas;

/**
 *
 * @author Adilson
 */
public class GTelaMultas extends javax.swing.JFrame {

    /**
     * Creates new form GTelaAbastecimento
     */
    public GTelaMultas() {
	initComponents();
	setBounds(300,50,700,650);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxMultasPlacaVeiculo = new javax.swing.JComboBox<>();
        jComboBoxMultasMotorista = new javax.swing.JComboBox<>();
        jComboBoxMultasSetor = new javax.swing.JComboBox<>();
        jLabelMultasPlacaVeiculo = new javax.swing.JLabel();
        jLabelMultasMotorista = new javax.swing.JLabel();
        jLabelMultasSetor = new javax.swing.JLabel();
        jLabelMultasIDVeiculo = new javax.swing.JLabel();
        jLabelMultasIDMotorista = new javax.swing.JLabel();
        jLabelMultasIDSetor = new javax.swing.JLabel();
        jLabelMultasData = new javax.swing.JLabel();
        jLabelMultasCamposObrigatorios = new javax.swing.JLabel();
        jButtonMultasSalvar = new javax.swing.JButton();
        jButtonMultasLimpar = new javax.swing.JButton();
        jLabelMultasFoto = new javax.swing.JLabel();
        jLabelMultasDescricao = new javax.swing.JLabel();
        jLabelMultasPesquisarID = new javax.swing.JLabel();
        jTextFieldMultasPesquisarID = new javax.swing.JTextField();
        jButtonMultasAlterar = new javax.swing.JButton();
        jButtonMultasExlcuir = new javax.swing.JButton();
        jTextFieldMultasData = new javax.swing.JTextField();
        jTextFieldMultasValor = new javax.swing.JTextField();
        jLabelMultasValor = new javax.swing.JLabel();
        jLabelMultasPontos = new javax.swing.JLabel();
        jTextFieldMultasPontos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMultasDescricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Multas");

        jComboBoxMultasPlacaVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABC 3030", "ABC 4444" }));

        jComboBoxMultasMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adilson", "Juca Bala", "Zé Bolha" }));

        jComboBoxMultasSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor A", "Setor B", "Setor C" }));

        jLabelMultasPlacaVeiculo.setText("*Placa Veiculo:");

        jLabelMultasMotorista.setText("*Motorista:");

        jLabelMultasSetor.setText("*Setor:");

        jLabelMultasIDVeiculo.setText("IDVeiculo");

        jLabelMultasIDMotorista.setText("IDMotorista");

        jLabelMultasIDSetor.setText("IDSetor");

        jLabelMultasData.setText("*Data:");

        jLabelMultasCamposObrigatorios.setText("* Campos Obrigatórios.");

        jButtonMultasSalvar.setText("Salvar");

        jButtonMultasLimpar.setText("Limpar");

        jLabelMultasFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/5Multa.png"))); // NOI18N

        jLabelMultasDescricao.setText("Descrição:");

        jLabelMultasPesquisarID.setText("Pesquisar ID:");

        jButtonMultasAlterar.setText("Alterar");

        jButtonMultasExlcuir.setText("Excluir");

        jLabelMultasValor.setText("*Valor:");

        jLabelMultasPontos.setText("Pontos:");

        jTextAreaMultasDescricao.setColumns(20);
        jTextAreaMultasDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMultasDescricao);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/pesquisar 20x20.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelMultasDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMultasPlacaVeiculo)
                                            .addComponent(jLabelMultasMotorista)
                                            .addComponent(jLabelMultasSetor)
                                            .addComponent(jLabelMultasPontos)
                                            .addComponent(jLabelMultasData)))
                                    .addComponent(jLabelMultasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldMultasPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxMultasPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxMultasMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxMultasSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMultasData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMultasValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelMultasIDMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelMultasIDVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addComponent(jLabelMultasIDSetor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabelMultasFoto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabelMultasCamposObrigatorios))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMultasPesquisarID)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMultasPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jButtonMultasSalvar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonMultasLimpar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonMultasAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonMultasExlcuir)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMultasFoto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelMultasPesquisarID)
                                .addComponent(jTextFieldMultasPesquisarID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMultasPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMultasPlacaVeiculo)
                            .addComponent(jLabelMultasIDVeiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxMultasMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMultasMotorista)
                            .addComponent(jLabelMultasIDMotorista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMultasIDSetor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxMultasSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMultasSetor)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMultasData)
                            .addComponent(jTextFieldMultasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMultasValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMultasValor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMultasPontos)
                    .addComponent(jTextFieldMultasPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMultasDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMultasSalvar)
                    .addComponent(jButtonMultasLimpar)
                    .addComponent(jButtonMultasAlterar)
                    .addComponent(jButtonMultasExlcuir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMultasCamposObrigatorios)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GTelaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GTelaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GTelaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GTelaMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GTelaMultas().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonMultasAlterar;
    private javax.swing.JButton jButtonMultasExlcuir;
    private javax.swing.JButton jButtonMultasLimpar;
    private javax.swing.JButton jButtonMultasSalvar;
    private javax.swing.JComboBox<String> jComboBoxMultasMotorista;
    private javax.swing.JComboBox<String> jComboBoxMultasPlacaVeiculo;
    private javax.swing.JComboBox<String> jComboBoxMultasSetor;
    private javax.swing.JLabel jLabelMultasCamposObrigatorios;
    private javax.swing.JLabel jLabelMultasData;
    private javax.swing.JLabel jLabelMultasDescricao;
    private javax.swing.JLabel jLabelMultasFoto;
    private javax.swing.JLabel jLabelMultasIDMotorista;
    private javax.swing.JLabel jLabelMultasIDSetor;
    private javax.swing.JLabel jLabelMultasIDVeiculo;
    private javax.swing.JLabel jLabelMultasMotorista;
    private javax.swing.JLabel jLabelMultasPesquisarID;
    private javax.swing.JLabel jLabelMultasPlacaVeiculo;
    private javax.swing.JLabel jLabelMultasPontos;
    private javax.swing.JLabel jLabelMultasSetor;
    private javax.swing.JLabel jLabelMultasValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMultasDescricao;
    private javax.swing.JTextField jTextFieldMultasData;
    private javax.swing.JTextField jTextFieldMultasPesquisarID;
    private javax.swing.JTextField jTextFieldMultasPontos;
    private javax.swing.JTextField jTextFieldMultasValor;
    // End of variables declaration//GEN-END:variables
}
