/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frotaveiculos.telas;

import com.frotaveiculos.dal.ModuloConexao;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
//import net.sf.jasperreports.engine.JRResultSetDataSource;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Adilson
 */
public class TelaPrincipal extends javax.swing.JFrame {

        //atributos
    Connection conexao = null;
    PreparedStatement pst = null;//PreparedStatement: conjunto de bibliotecas - Variavel pst
    ResultSet rs = null; //exibir o resultado das instruções slq
    
    /**
     * Creates new form GTelaPrincipal
     */
    public TelaPrincipal() {
	initComponents();
	setBounds(300, 50, 700, 650);
	try {
	    conexao = ModuloConexao.conector();
	} catch (ClassNotFoundException ex) {
	    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabelNomeTela = new javax.swing.JLabel();
        jLabelUsuarioTela = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuArquivo = new javax.swing.JMenu();
        MenuItemSair = new javax.swing.JMenuItem();
        MenuCadastro = new javax.swing.JMenu();
        MenuItemCadastrarMotorista = new javax.swing.JMenuItem();
        MenuItemCadastrarVeiculo = new javax.swing.JMenuItem();
        MenuItemCadastrarSetor = new javax.swing.JMenuItem();
        MenuInputs = new javax.swing.JMenu();
        MenuItemAbastecimento = new javax.swing.JMenuItem();
        MenuItemDeslocamento = new javax.swing.JMenuItem();
        MenuItemManutencao = new javax.swing.JMenuItem();
        MenuItemTrocaOleo = new javax.swing.JMenuItem();
        MenuItemMultas = new javax.swing.JMenuItem();
        MenuItemSeguro = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelatorioAbastecimento = new javax.swing.JMenuItem();
        jMenuItemRelatorioDeslocamento = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de frota de veículos");
        setExtendedState(6);

        desktopPane.setBackground(java.awt.SystemColor.controlHighlight);
        desktopPane.setForeground(java.awt.SystemColor.controlHighlight);

        jLabelNomeTela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNomeTela.setText("Nome");
        desktopPane.add(jLabelNomeTela);
        jLabelNomeTela.setBounds(80, 10, 90, 15);

        jLabelUsuarioTela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelUsuarioTela.setText("Usuário:");
        desktopPane.add(jLabelUsuarioTela);
        jLabelUsuarioTela.setBounds(20, 10, 50, 15);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconAbastecimento.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(20, 40, 120, 70);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconDeslocamento.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton2);
        jButton2.setBounds(20, 140, 120, 70);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconManutencao.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton3);
        jButton3.setBounds(20, 240, 120, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconTrocaOleo.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton4);
        jButton4.setBounds(20, 340, 120, 70);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconMulta.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton5);
        jButton5.setBounds(20, 440, 120, 70);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/frotaveiculos/icones/IconSeguro.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton6);
        jButton6.setBounds(20, 540, 120, 70);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abastecimento");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(20, 110, 120, 14);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Deslocamento");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(20, 210, 120, 14);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manutenção");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(20, 310, 120, 14);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Troca de Óleo");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(20, 410, 120, 14);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Multas");
        desktopPane.add(jLabel5);
        jLabel5.setBounds(20, 510, 120, 14);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seguro");
        desktopPane.add(jLabel6);
        jLabel6.setBounds(20, 610, 120, 14);

        MenuArquivo.setMnemonic('f');
        MenuArquivo.setText("Arquivo");

        MenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSair.setMnemonic('x');
        MenuItemSair.setText("Sair");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });
        MenuArquivo.add(MenuItemSair);

        menuBar.add(MenuArquivo);

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setEnabled(false);

        MenuItemCadastrarMotorista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemCadastrarMotorista.setText("Cadastrar Motorista");
        MenuItemCadastrarMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastrarMotoristaActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemCadastrarMotorista);

        MenuItemCadastrarVeiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemCadastrarVeiculo.setText("Cadastrar Veículo");
        MenuItemCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastrarVeiculoActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemCadastrarVeiculo);

        MenuItemCadastrarSetor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuItemCadastrarSetor.setText("Cadastrar Setor");
        MenuItemCadastrarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastrarSetorActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuItemCadastrarSetor);

        menuBar.add(MenuCadastro);

        MenuInputs.setMnemonic('e');
        MenuInputs.setText("Inputs");

        MenuItemAbastecimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenuItemAbastecimento.setMnemonic('t');
        MenuItemAbastecimento.setText("Abastecimento");
        MenuItemAbastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAbastecimentoActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemAbastecimento);

        MenuItemDeslocamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        MenuItemDeslocamento.setMnemonic('y');
        MenuItemDeslocamento.setText("Deslocamento");
        MenuItemDeslocamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDeslocamentoActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemDeslocamento);

        MenuItemManutencao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        MenuItemManutencao.setMnemonic('p');
        MenuItemManutencao.setText("Manutenção");
        MenuItemManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemManutencaoActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemManutencao);

        MenuItemTrocaOleo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        MenuItemTrocaOleo.setMnemonic('d');
        MenuItemTrocaOleo.setText("Troca de Óleo");
        MenuItemTrocaOleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTrocaOleoActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemTrocaOleo);

        MenuItemMultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuItemMultas.setText("Multas");
        MenuItemMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemMultasActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemMultas);

        MenuItemSeguro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSeguro.setText("Seguro");
        MenuItemSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSeguroActionPerformed(evt);
            }
        });
        MenuInputs.add(MenuItemSeguro);

        menuBar.add(MenuInputs);

        MenuRelatorio.setText("Relatórios");
        MenuRelatorio.setEnabled(false);
        MenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelatorioActionPerformed(evt);
            }
        });

        jMenuItemRelatorioAbastecimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelatorioAbastecimento.setText("Relatório Abastecimento");
        jMenuItemRelatorioAbastecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioAbastecimentoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenuItemRelatorioAbastecimento);

        jMenuItemRelatorioDeslocamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRelatorioDeslocamento.setText("Relatório Deslocamento");
        jMenuItemRelatorioDeslocamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatorioDeslocamentoActionPerformed(evt);
            }
        });
        MenuRelatorio.add(jMenuItemRelatorioDeslocamento);

        menuBar.add(MenuRelatorio);

        MenuAjuda.setMnemonic('h');
        MenuAjuda.setText("Ajuda");

        MenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        MenuItemSobre.setMnemonic('a');
        MenuItemSobre.setText("Sobre");
        MenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuItemSobre);

        menuBar.add(MenuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(753, 714));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed
	int sair = JOptionPane.showConfirmDialog(null, " Tem certeza que deseja sair? ", " Atenção ", JOptionPane.YES_NO_OPTION);
	if (sair == JOptionPane.YES_OPTION){
	    System.exit(0);
	}
	//System.exit(0);
    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void MenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSobreActionPerformed
	GTelaSobre frameGTelaSobre = new GTelaSobre();
	frameGTelaSobre.setVisible(true);

    }//GEN-LAST:event_MenuItemSobreActionPerformed

    private void MenuItemDeslocamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDeslocamentoActionPerformed
	GTelaDeslocamento frameGTelaDeslocamento = new GTelaDeslocamento();
	frameGTelaDeslocamento.setVisible(true);
    }//GEN-LAST:event_MenuItemDeslocamentoActionPerformed

    private void MenuItemCadastrarMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastrarMotoristaActionPerformed
	GTelaCadastroMotorista frameGTelaCadastroMotorista = new GTelaCadastroMotorista();
	frameGTelaCadastroMotorista.setVisible(true);
    }//GEN-LAST:event_MenuItemCadastrarMotoristaActionPerformed

    private void MenuItemCadastrarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastrarSetorActionPerformed
	/*GTelaCadastroSetor frameGTelaCadastroSetor = new GTelaCadastroSetor();
	frameGTelaCadastroSetor.setVisible(true);*/
    }//GEN-LAST:event_MenuItemCadastrarSetorActionPerformed

    private void MenuItemCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastrarVeiculoActionPerformed
	GTelaCadastroVeiculo frameGTelaCadastroVeiculo = new GTelaCadastroVeiculo();
	frameGTelaCadastroVeiculo.setVisible(true);
    }//GEN-LAST:event_MenuItemCadastrarVeiculoActionPerformed

    private void MenuItemAbastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAbastecimentoActionPerformed
	GTelaAbastecimento frameGTelaAbastecimento = new GTelaAbastecimento();
	frameGTelaAbastecimento.setVisible(true);
	
    }//GEN-LAST:event_MenuItemAbastecimentoActionPerformed

    private void MenuItemManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemManutencaoActionPerformed
	GTelaManutencao frameGTelaManutencao = new GTelaManutencao();
	frameGTelaManutencao.setVisible(true);
    }//GEN-LAST:event_MenuItemManutencaoActionPerformed

    private void MenuItemTrocaOleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTrocaOleoActionPerformed
	GTelaTrocaOleo frameGTelaTrocaOleo = new GTelaTrocaOleo();
	frameGTelaTrocaOleo.setVisible(true);
    }//GEN-LAST:event_MenuItemTrocaOleoActionPerformed

    private void MenuItemMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMultasActionPerformed
	GTelaMultas frameGTelaMultas = new GTelaMultas();
	frameGTelaMultas.setVisible(true);

    }//GEN-LAST:event_MenuItemMultasActionPerformed

    private void MenuItemSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSeguroActionPerformed
	GTelaSeguro frameGTelaSeguro = new GTelaSeguro();
	frameGTelaSeguro.setVisible(true);
    }//GEN-LAST:event_MenuItemSeguroActionPerformed

    private void jMenuItemRelatorioAbastecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioAbastecimentoActionPerformed
	int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório? ","Atenção ", JOptionPane.YES_NO_OPTION);
	if (confirma == JOptionPane.YES_OPTION){
	    //imprimindo relatório com framework JasperReport
	    
	    try {
		//Usando a Classe JasperPrint que esta dentro das bibliotecas para preparar a impressão.
//		JasperPrint RelatorioAbastecimento = JasperFillManager.fillReport("C:\\Users\\Adilson\\iReports\\RelatorioAbastecimento.jasper",null,conexao);

		//A linha a baixo exibe o relatório através da classe jasperViewer.
//		JasperViewer.viewReport(RelatorioAbastecimento,false);
	    } catch (Exception e) {
		JOptionPane.showMessageDialog(null,"Erro ao chamar o relatório!\nErro: "+ e);
	    }
	}
    }//GEN-LAST:event_jMenuItemRelatorioAbastecimentoActionPerformed

    private void MenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRelatorioActionPerformed

    private void jMenuItemRelatorioDeslocamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatorioDeslocamentoActionPerformed
	 	int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório? ","Atenção ", JOptionPane.YES_NO_OPTION);
	if (confirma == JOptionPane.YES_OPTION){
	    //imprimindo relatório com framework JasperReport
	    
	    try {
		//Usando a Classe JasperPrint que esta dentro das bibliotecas para preparar a impressão.
//		JasperPrint RelatorioDeslocamento = JasperFillManager.fillReport("C:\\Users\\Adilson\\iReports\\RelatorioDeslocamento.jasper",null,conexao);

		//A linha a baixo exibe o relatório através da classe jasperViewer.
//		JasperViewer.viewReport(RelatorioDeslocamento,false);
	    } catch (Exception e) {
		JOptionPane.showMessageDialog(null,"Erro ao chamar o relatório!\nErro: "+ e);
	    }
	}
    }//GEN-LAST:event_jMenuItemRelatorioDeslocamentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	GTelaAbastecimento frameGTelaAbastecimento = new GTelaAbastecimento();
	frameGTelaAbastecimento.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
	GTelaDeslocamento frameGTelaDeslocamento = new GTelaDeslocamento();
	frameGTelaDeslocamento.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	GTelaManutencao frameGTelaManutencao = new GTelaManutencao();
	frameGTelaManutencao.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
	GTelaTrocaOleo frameGTelaTrocaOleo = new GTelaTrocaOleo();
	frameGTelaTrocaOleo.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
	GTelaMultas frameGTelaMultas = new GTelaMultas();
	frameGTelaMultas.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
	GTelaSeguro frameGTelaSeguro = new GTelaSeguro();
	frameGTelaSeguro.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new TelaPrincipal().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenu MenuArquivo;
    public static javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuInputs;
    private javax.swing.JMenuItem MenuItemAbastecimento;
    private javax.swing.JMenuItem MenuItemCadastrarMotorista;
    private javax.swing.JMenuItem MenuItemCadastrarSetor;
    private javax.swing.JMenuItem MenuItemCadastrarVeiculo;
    private javax.swing.JMenuItem MenuItemDeslocamento;
    private javax.swing.JMenuItem MenuItemManutencao;
    private javax.swing.JMenuItem MenuItemMultas;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenuItem MenuItemSeguro;
    private javax.swing.JMenuItem MenuItemSobre;
    private javax.swing.JMenuItem MenuItemTrocaOleo;
    public static javax.swing.JMenu MenuRelatorio;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabelNomeTela;
    private javax.swing.JLabel jLabelUsuarioTela;
    private javax.swing.JMenuItem jMenuItemRelatorioAbastecimento;
    private javax.swing.JMenuItem jMenuItemRelatorioDeslocamento;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
